name: Validate

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  validate:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get build dependencies
        run: apt-get update && apt-get -y install plantuml
      - name: Validate LaTeX document
        run: |
          make -B main.tex
      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf
